### ISSUE TITLE
user_episodes table 

### ISSUE THREAD

**Issue by nisozakuto** [lsysophia/MSN-MTDB#28]
20200829191200-create_user_episodes_table.sql had user_series as its table name. I changed that to user_episodes assuming there was a mistake there. 

I need help on Line 8
`series_id INTEGER NOT NULL REFERENCES user_series(imdb_id) ON DELETE CASCADE`
Could you please confirm is this is correct or does it need to be changed to user_episodes?

Thank you

**Comment by Schlaffmatthewj** [comment]
I'll have to wait to answer when I can open.. thanks
